// GENERATED by scripts/build_forest_overlay.mjs — do not edit by hand.
//
// The client's forest-and-hornbills drawing, tinted right down and flattened
// onto the cream so it can lie under the type of `03 · The Forest`. Source is
// `Forest-illustrations/forest-overlay.jfif`; the encoded files are
// `public/brand/forest-overlay-{paper,paperDeep}-*.webp`.
//
// **The strength is enforced at build time, not asserted here.** The script
// composites every pixel onto both creams, finds the darkest result, and
// throws if `PALETTE.dim` would fall under 4.5:1 on it. Worst measured case
// at the strength below: **4.56:1**.
//
// **Two files, one per cream, because the tint is baked rather than blended.**
// That flattening is what takes it from 282 KB to ~6 KB — see the build script.
//
// **The source is only 2752px wide** and nothing wider is emitted; upscaling
// into the file would bake softness in and hide it. The browser therefore
// stretches it on a wide screen, which is tolerable for a near-flat texture
// and would not be for a photograph. Non-negotiable #11 sets 1400px as the
// floor for edge-to-edge imagery; a re-render at 2800px would remove the
// compromise for about 20 KB.

export const FOREST_OVERLAY = {
  /** Encoded widths. Capped at the source's own resolution. */
  widths: [640, 1024, 1600] as const,
  /** The one `src` a browser without `srcset` support would take. */
  fallback: 1600,
  /** Intrinsic size of the drawing. */
  width: 2752,
  height: 1536,
  /** How strongly its darkest ink prints on the cream. */
  strength: 0.267,
  /** Blacks are lifted to this before becoming tint — see the build script. */
  inkFloor: 20,
  /** Worst-case contrast of the page's text colours over the darkest part of it. */
  worstContrast: 4.56,
} as const;
