// GENERATED by scripts/build_lantern.mjs — do not edit by hand.
//
// The client's watercolour lantern, as hung under `after-dark` into
// `06 · The Lantern Hour`. Source artwork is
// `reference/client-art/hanging-lantern.png`; the encoded files are
// `public/brand/lantern-*.webp`.
//
// **This is the swap point.** A new drawing means dropping a new PNG over the
// source and re-running the script. Nothing else changes: the component reads
// only what is below, and `lib/lantern-art.test.ts` holds any replacement to the
// same guarantees — including that the source still needs its white ground cut,
// which is the thing about this artwork that no other check would notice.

export const LANTERN = {
  /** Encoded widths, in CSS pixels of drawn width. Paired with a `sizes` expression. */
  widths: [200, 320, 440, 640] as const,
  /** The one `src` a browser without `srcset` support would take. */
  fallback: 320,
  /** Intrinsic size of the trimmed artwork, so nothing can disagree about its aspect. */
  width: 1277,
  height: 1861,
  /**
   * The top of the chain, as a fraction of the drawn box — the point the lantern
   * hangs from and therefore the point it swings about. Measured from the
   * artwork's own ink, not chosen. A pendulum pivoting anywhere else reads as a
   * picture being rotated rather than as an object hanging.
   */
  pivot: { x: 0.36, y: 0 },
} as const;
