// GENERATED by scripts/build_leaf.mjs — do not edit by hand.
//
// The client's hand-drawn mahua leaf, as worn by the cursor. Source artwork is
// `reference/client-art/hand-drawn-leaf.png`; the encoded files are
// `public/brand/leaf-*.webp`.
//
// **This is the swap point.** A new drawing means dropping a new PNG over the
// source and re-running the script. Nothing else changes: the component reads
// only what is below, and `lib/leaf-art.test.ts` holds any replacement to the
// same guarantees.

export const LEAF = {
  /**
   * Encoded widths, one per screen density, as exact multiples of the width the
   * cursor draws at. The component pairs them with `1x`/`2x`/`3x` descriptors —
   * see the build script for why this is not a `sizes` attribute.
   */
  widths: [26, 52, 78] as const,
  /** The one `src` a browser without `srcset` support would take. */
  fallback: 26,
  /** The CSS width the cursor draws at; its height is `CURSOR.sizePx`. */
  drawnWidth: 26,
  /** Intrinsic size of the trimmed artwork, so nothing can disagree about its aspect. */
  width: 196,
  height: 212,
  /**
   * The leaf's apex, as a fraction of the drawn box — the point that sits exactly
   * on the pointer, as an arrow cursor's tip does. Measured from the artwork's own
   * ink, not chosen.
   */
  hotspot: { x: 0.018, y: 0.005 },
} as const;
