/**
 * Curated photography for the Mahua Resorts site.
 *
 * Generated by scripts/build_images.mjs from reference/mockup-media and
 * reference/wp-media (see lib/media-manifest.ts, `as const` so `MediaId` is
 * a literal union — a typo'd id is a build error here, not a runtime
 * `undefined`).
 */
import { MANIFEST } from "./media-manifest";

export type MediaId = (typeof MANIFEST)[number]["id"];

/** The brand guidelines' own photography taxonomy — see CLAUDE.md. */
export type MediaCategory = "lanternHour" | "forest" | "lodgeLife" | "details";

export type MediaOrientation = "landscape" | "portrait" | "square";

/**
 * One emitted responsive tier. `scripts/build_images.mjs` has always written
 * several widths per photograph; until 4 Aug 2026 the manifest recorded only the
 * largest, so every `<img>` on the page pointed at it and a 390px phone
 * downloaded the 1440-wide hero. These are what `ui/Photo.tsx` turns into a
 * `srcset` — the widths were already on disk, just unreferenced.
 *
 * `width`/`height` are the dimensions sharp actually encoded, read back off the
 * buffer it returned, and `lib/media.test.ts` re-reads every one of them off
 * disk rather than trusting the build script's bookkeeping.
 */
export type MediaSource = {
  width: number;
  height: number;
  avif: string;
  webp: string;
};

export type MediaEntry = {
  id: MediaId;
  alt: string;
  /** The largest tier's width — i.e. `sources[sources.length - 1].width`. */
  width: number;
  height: number;
  avif: string;
  webp: string;
  jpg: string;
  blur: string;
  /** Ascending by width. Never empty; the last entry is the canonical one above. */
  sources: readonly MediaSource[];
  category: MediaCategory;
  orientation: MediaOrientation;
  /** Only true when width >= 1400px — see CLAUDE.md non-negotiable #10. */
  fullBleedSafe: boolean;
};

export const MEDIA: readonly MediaEntry[] = MANIFEST;

export function media(id: MediaId): MediaEntry {
  const found = MEDIA.find((m) => m.id === id);
  if (!found) throw new Error(`Unknown media id: ${id}`);
  return found;
}
