/**
 * Curated photography for the Mahua Resorts site.
 *
 * Generated by scripts/build_images.mjs from reference/mockup-media and
 * reference/wp-media (see lib/media-manifest.ts, `as const` so `MediaId` is
 * a literal union — a typo'd id is a build error here, not a runtime
 * `undefined`).
 */
import { MANIFEST } from "./media-manifest";

export type MediaId = (typeof MANIFEST)[number]["id"];

/** The brand guidelines' own photography taxonomy — see CLAUDE.md. */
export type MediaCategory = "lanternHour" | "forest" | "lodgeLife" | "details";

export type MediaOrientation = "landscape" | "portrait" | "square";

export type MediaEntry = {
  id: MediaId;
  alt: string;
  width: number;
  height: number;
  avif: string;
  webp: string;
  jpg: string;
  blur: string;
  category: MediaCategory;
  orientation: MediaOrientation;
  /** Only true when width >= 1400px — see CLAUDE.md non-negotiable #10. */
  fullBleedSafe: boolean;
};

export const MEDIA: readonly MediaEntry[] = MANIFEST;

export function media(id: MediaId): MediaEntry {
  const found = MEDIA.find((m) => m.id === id);
  if (!found) throw new Error(`Unknown media id: ${id}`);
  return found;
}
