// GENERATED FILE — do not edit by hand.
// Produced by scripts/build_images.mjs from reference/mockup-media and reference/wp-media.
// Run `node scripts/build_images.mjs` to regenerate.

export const MANIFEST = [
  {
    id: "lantern-bridge-dusk",
    alt: "A lantern-lit wooden bridge leading into Mahua Vann's forest canopy at dusk.",
    width: 1300,
    height: 866,
    avif: "/media/lantern-bridge-dusk-1300.avif",
    webp: "/media/lantern-bridge-dusk-1300.webp",
    jpg: "/media/lantern-bridge-dusk-1300.jpg",
    blur: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAwCdASoYABAALrV2u12jqampiYC0SygGN6Id/B2kMr5NBhAA/vd7LIQvovaA2pQWu5Fjgq6eF7AA",
    sources: [
      { width: 400, height: 266, avif: "/media/lantern-bridge-dusk-400.avif", webp: "/media/lantern-bridge-dusk-400.webp" },
      { width: 640, height: 426, avif: "/media/lantern-bridge-dusk-640.avif", webp: "/media/lantern-bridge-dusk-640.webp" },
      { width: 768, height: 512, avif: "/media/lantern-bridge-dusk-768.avif", webp: "/media/lantern-bridge-dusk-768.webp" },
      { width: 960, height: 640, avif: "/media/lantern-bridge-dusk-960.avif", webp: "/media/lantern-bridge-dusk-960.webp" },
      { width: 1200, height: 799, avif: "/media/lantern-bridge-dusk-1200.avif", webp: "/media/lantern-bridge-dusk-1200.webp" },
      { width: 1300, height: 866, avif: "/media/lantern-bridge-dusk-1300.avif", webp: "/media/lantern-bridge-dusk-1300.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "bonfire-dinner",
    alt: "A bonfire dinner laid beneath lantern-lit trees under a starlit sky.",
    width: 1100,
    height: 733,
    avif: "/media/bonfire-dinner-1100.avif",
    webp: "/media/bonfire-dinner-1100.webp",
    jpg: "/media/bonfire-dinner-1100.jpg",
    blur: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoYABAAPu1kqU4ppaOiMAgBMB2JaACdMoRwACnKKujHR0GVybAA/vKmfkgW4rYPK3YAfvUUxMljN0SiACBp7Q+AlZh3YBpJ2nZLm3ewhAA=",
    sources: [
      { width: 400, height: 267, avif: "/media/bonfire-dinner-400.avif", webp: "/media/bonfire-dinner-400.webp" },
      { width: 640, height: 426, avif: "/media/bonfire-dinner-640.avif", webp: "/media/bonfire-dinner-640.webp" },
      { width: 768, height: 512, avif: "/media/bonfire-dinner-768.avif", webp: "/media/bonfire-dinner-768.webp" },
      { width: 960, height: 640, avif: "/media/bonfire-dinner-960.avif", webp: "/media/bonfire-dinner-960.webp" },
      { width: 1100, height: 733, avif: "/media/bonfire-dinner-1100.avif", webp: "/media/bonfire-dinner-1100.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "veranda-through-leaves",
    alt: "A lantern-lit veranda glimpsed through leaves at dusk, a rattan lampshade glowing above the tables.",
    width: 1100,
    height: 1650,
    avif: "/media/veranda-through-leaves-1100.avif",
    webp: "/media/veranda-through-leaves-1100.webp",
    jpg: "/media/veranda-through-leaves-1100.jpg",
    blur: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBQCdASoYACQAPu1cp04ppKMiMBqqqTAdiWNh4FA/jQFE3VIuPXCJyNlfjZFwCJTKFkAA/uoaye1n4d9rP5cULl3hMdnnlWujMvqQbSb4QMyG8DyFRDl0+UqgjYH54OiDQUaBTiPqIVWCLGMQ4pu2ji/Uxaiby1dVcNTRl/XgyGuE6ijVdpHxZ7Rmca3wWcxsgAAA",
    sources: [
      { width: 400, height: 600, avif: "/media/veranda-through-leaves-400.avif", webp: "/media/veranda-through-leaves-400.webp" },
      { width: 640, height: 960, avif: "/media/veranda-through-leaves-640.avif", webp: "/media/veranda-through-leaves-640.webp" },
      { width: 768, height: 1152, avif: "/media/veranda-through-leaves-768.avif", webp: "/media/veranda-through-leaves-768.webp" },
      { width: 960, height: 1440, avif: "/media/veranda-through-leaves-960.avif", webp: "/media/veranda-through-leaves-960.webp" },
      { width: 1100, height: 1650, avif: "/media/veranda-through-leaves-1100.avif", webp: "/media/veranda-through-leaves-1100.webp" },
    ],
    category: "lanternHour",
    orientation: "portrait",
    fullBleedSafe: false,
  },
  {
    id: "mahua-tola-pool",
    alt: "The pool at Mahua Tola lit by lanterns against a fading dusk sky.",
    width: 1440,
    height: 959,
    avif: "/media/mahua-tola-pool-1440.avif",
    webp: "/media/mahua-tola-pool-1440.webp",
    jpg: "/media/mahua-tola-pool-1440.jpg",
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCdICXCcdUjlEDgQvZsKAAA+nEZNhmaJVXsZ4rAO/h0YZW4MMjG32Ynvc83Rsyyg1Xswo3I5brTtbGwCLibD7yoAA==",
    sources: [
      { width: 400, height: 267, avif: "/media/mahua-tola-pool-400.avif", webp: "/media/mahua-tola-pool-400.webp" },
      { width: 640, height: 426, avif: "/media/mahua-tola-pool-640.avif", webp: "/media/mahua-tola-pool-640.webp" },
      { width: 768, height: 512, avif: "/media/mahua-tola-pool-768.avif", webp: "/media/mahua-tola-pool-768.webp" },
      { width: 960, height: 640, avif: "/media/mahua-tola-pool-960.avif", webp: "/media/mahua-tola-pool-960.webp" },
      { width: 1200, height: 800, avif: "/media/mahua-tola-pool-1200.avif", webp: "/media/mahua-tola-pool-1200.webp" },
      { width: 1440, height: 959, avif: "/media/mahua-tola-pool-1440.avif", webp: "/media/mahua-tola-pool-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "reception-path-dusk",
    alt: "The path to a lantern-lit reception veranda at dusk, banana leaves catching the last light.",
    width: 1440,
    height: 960,
    avif: "/media/reception-path-dusk-1440.avif",
    webp: "/media/reception-path-dusk-1440.webp",
    jpg: "/media/reception-path-dusk-1440.jpg",
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwBACdASoYABAAPu1kqk2ppaQiMAgBMB2JYgCdMoACYrc+HOUrfXrD8iAA/uaCvD0dRiQmUmpi3gnDGPmpbB6+zouBa8yJHEJk2V1yfB4x7jNJf70a2nLLArDaqaZy/cpRJ+1q1B5kS0oUfQAciJbr5VwAAA==",
    sources: [
      { width: 400, height: 266, avif: "/media/reception-path-dusk-400.avif", webp: "/media/reception-path-dusk-400.webp" },
      { width: 640, height: 427, avif: "/media/reception-path-dusk-640.avif", webp: "/media/reception-path-dusk-640.webp" },
      { width: 768, height: 512, avif: "/media/reception-path-dusk-768.avif", webp: "/media/reception-path-dusk-768.webp" },
      { width: 960, height: 640, avif: "/media/reception-path-dusk-960.avif", webp: "/media/reception-path-dusk-960.webp" },
      { width: 1200, height: 800, avif: "/media/reception-path-dusk-1200.avif", webp: "/media/reception-path-dusk-1200.webp" },
      { width: 1440, height: 960, avif: "/media/reception-path-dusk-1440.avif", webp: "/media/reception-path-dusk-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "birding-cairn-dusk",
    alt: "A cairn of hand-painted bird names beside the path to a lantern-lit veranda at dusk.",
    width: 1440,
    height: 960,
    avif: "/media/birding-cairn-dusk-1440.avif",
    webp: "/media/birding-cairn-dusk-1440.webp",
    jpg: "/media/birding-cairn-dusk-1440.jpg",
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoYABAAPu1iqk2ppaQiMAgBMB2JYwDCgBuJ2kk/Qr16GdwmhAAA/mD6QlhMwXILzl8HjK57AkB+2+TaaqrGU+x4lBLb2aPt57nXL8YSDHfXR18H88vv21ert34XgOv98zIqlECgAAA=",
    sources: [
      { width: 400, height: 266, avif: "/media/birding-cairn-dusk-400.avif", webp: "/media/birding-cairn-dusk-400.webp" },
      { width: 640, height: 427, avif: "/media/birding-cairn-dusk-640.avif", webp: "/media/birding-cairn-dusk-640.webp" },
      { width: 768, height: 512, avif: "/media/birding-cairn-dusk-768.avif", webp: "/media/birding-cairn-dusk-768.webp" },
      { width: 960, height: 640, avif: "/media/birding-cairn-dusk-960.avif", webp: "/media/birding-cairn-dusk-960.webp" },
      { width: 1200, height: 800, avif: "/media/birding-cairn-dusk-1200.avif", webp: "/media/birding-cairn-dusk-1200.webp" },
      { width: 1440, height: 960, avif: "/media/birding-cairn-dusk-1440.avif", webp: "/media/birding-cairn-dusk-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "lodge-facade-night",
    alt: "A two-storey lodge building lit against the night sky, framed by bamboo.",
    width: 1440,
    height: 961,
    avif: "/media/lodge-facade-night-1440.avif",
    webp: "/media/lodge-facade-night-1440.webp",
    jpg: "/media/lodge-facade-night-1440.jpg",
    blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoYABAAPu1orU6ppiSiMAgBMB2JYgAAUqj186zjLsM3ZwAA/vQy2zOFqJtkiGt/4i32mrKoAYS/Jx6V4cVN29y6HDAQsbbAbVohEAAA",
    sources: [
      { width: 400, height: 267, avif: "/media/lodge-facade-night-400.avif", webp: "/media/lodge-facade-night-400.webp" },
      { width: 640, height: 427, avif: "/media/lodge-facade-night-640.avif", webp: "/media/lodge-facade-night-640.webp" },
      { width: 768, height: 512, avif: "/media/lodge-facade-night-768.avif", webp: "/media/lodge-facade-night-768.webp" },
      { width: 960, height: 641, avif: "/media/lodge-facade-night-960.avif", webp: "/media/lodge-facade-night-960.webp" },
      { width: 1200, height: 801, avif: "/media/lodge-facade-night-1200.avif", webp: "/media/lodge-facade-night-1200.webp" },
      { width: 1440, height: 961, avif: "/media/lodge-facade-night-1440.avif", webp: "/media/lodge-facade-night-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "petal-table-night",
    alt: "A candlelit table strewn with bougainvillea petals on the night lawn, the lit veranda beyond.",
    width: 1440,
    height: 810,
    avif: "/media/petal-table-night-1440.avif",
    webp: "/media/petal-table-night-1440.webp",
    jpg: "/media/petal-table-night-1440.jpg",
    blur: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoYAA4APu1iqk4ppaQiMAgBMB2JQBOmUBDAAuBTofMRspzRIAD+7qFRmIvHTRD/g7Ez/IM7Lf6jtJa+Sifg/t1IwzFaeao9yj56yrjSsYvv3cGAaOYcxn2IiiuSE90kH6T47svir6w7YMAA",
    sources: [
      { width: 400, height: 225, avif: "/media/petal-table-night-400.avif", webp: "/media/petal-table-night-400.webp" },
      { width: 640, height: 360, avif: "/media/petal-table-night-640.avif", webp: "/media/petal-table-night-640.webp" },
      { width: 768, height: 432, avif: "/media/petal-table-night-768.avif", webp: "/media/petal-table-night-768.webp" },
      { width: 960, height: 540, avif: "/media/petal-table-night-960.avif", webp: "/media/petal-table-night-960.webp" },
      { width: 1200, height: 675, avif: "/media/petal-table-night-1200.avif", webp: "/media/petal-table-night-1200.webp" },
      { width: 1440, height: 810, avif: "/media/petal-table-night-1440.avif", webp: "/media/petal-table-night-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "bonfire-circle-night",
    alt: "A bonfire burning inside a ring of bamboo benches, the forest dark beyond the firelight.",
    width: 1440,
    height: 810,
    avif: "/media/bonfire-circle-night-1440.avif",
    webp: "/media/bonfire-circle-night-1440.webp",
    jpg: "/media/bonfire-circle-night-1440.jpg",
    blur: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JbAC06CHfwwl0ZvNY2eAA/vQben0GkGKOAnT9iGI2ar12/c8bBMMiCwiSMP3A5MkX5Lsr1UgAAA==",
    sources: [
      { width: 400, height: 225, avif: "/media/bonfire-circle-night-400.avif", webp: "/media/bonfire-circle-night-400.webp" },
      { width: 640, height: 360, avif: "/media/bonfire-circle-night-640.avif", webp: "/media/bonfire-circle-night-640.webp" },
      { width: 768, height: 432, avif: "/media/bonfire-circle-night-768.avif", webp: "/media/bonfire-circle-night-768.webp" },
      { width: 960, height: 540, avif: "/media/bonfire-circle-night-960.avif", webp: "/media/bonfire-circle-night-960.webp" },
      { width: 1200, height: 675, avif: "/media/bonfire-circle-night-1200.avif", webp: "/media/bonfire-circle-night-1200.webp" },
      { width: 1440, height: 810, avif: "/media/bonfire-circle-night-1440.avif", webp: "/media/bonfire-circle-night-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "tiger-golden-grass",
    alt: "A Bengal tiger moving through tall golden grass in the Pench forest.",
    width: 1440,
    height: 959,
    avif: "/media/tiger-golden-grass-1440.avif",
    webp: "/media/tiger-golden-grass-1440.webp",
    jpg: "/media/tiger-golden-grass-1440.jpg",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoYABAAPu1mqk4ppaOiMAgBMB2JZgCdMoADPL12xl0UQ0LOZ8AA/vKkKDHPJM3b1tHd68fDeE/i84ZQ3oolAkkqd3Yk//fFUnr/2sf20akm437nZRnQAAAA",
    sources: [
      { width: 400, height: 266, avif: "/media/tiger-golden-grass-400.avif", webp: "/media/tiger-golden-grass-400.webp" },
      { width: 640, height: 426, avif: "/media/tiger-golden-grass-640.avif", webp: "/media/tiger-golden-grass-640.webp" },
      { width: 768, height: 511, avif: "/media/tiger-golden-grass-768.avif", webp: "/media/tiger-golden-grass-768.webp" },
      { width: 960, height: 639, avif: "/media/tiger-golden-grass-960.avif", webp: "/media/tiger-golden-grass-960.webp" },
      { width: 1200, height: 799, avif: "/media/tiger-golden-grass-1200.avif", webp: "/media/tiger-golden-grass-1200.webp" },
      { width: 1440, height: 959, avif: "/media/tiger-golden-grass-1440.avif", webp: "/media/tiger-golden-grass-1440.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "tiger-pair-profile",
    alt: "A tiger in close profile, a second cat's flank passing just behind it.",
    width: 900,
    height: 1133,
    avif: "/media/tiger-pair-profile-900.avif",
    webp: "/media/tiger-pair-profile-900.webp",
    jpg: "/media/tiger-pair-profile-900.jpg",
    blur: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACQBQCdASoYAB4APtlcpE2oJaOiN/qoAQAbCWMAxNhVy5hG6yZw4XSiAAZLVP/mBoCfc7EgAAD+7qGZ0jLxmYwdYlypjBvh+482pPtYpLOumRKfmm1MOZ4s5d+0qKwZfYt5Lcmjbc6x/sxwDcODQlvW6hWGQG9v5HKDyGd+Hs0AAA==",
    sources: [
      { width: 400, height: 504, avif: "/media/tiger-pair-profile-400.avif", webp: "/media/tiger-pair-profile-400.webp" },
      { width: 640, height: 806, avif: "/media/tiger-pair-profile-640.avif", webp: "/media/tiger-pair-profile-640.webp" },
      { width: 768, height: 967, avif: "/media/tiger-pair-profile-768.avif", webp: "/media/tiger-pair-profile-768.webp" },
      { width: 900, height: 1133, avif: "/media/tiger-pair-profile-900.avif", webp: "/media/tiger-pair-profile-900.webp" },
    ],
    category: "forest",
    orientation: "portrait",
    fullBleedSafe: false,
  },
  {
    id: "leopard-on-rock",
    alt: "A leopard resting on a rock, framed by slender trees in dense forest.",
    width: 900,
    height: 1352,
    avif: "/media/leopard-on-rock-900.avif",
    webp: "/media/leopard-on-rock-900.webp",
    jpg: "/media/leopard-on-rock-900.jpg",
    blur: "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBQCdASoYACQAPu1wsFAppqSiqrgKATAdiWNmXNuNKAD+JWA3q3gnHi+EEXoQ/0oAAP7sjEn6swg8cPrQDkwR9bJihtX53ohR+ALFoj0ZsbredepvrQgQKOPIQygHtYfIICiHqgoN3c4VRKRzsh7ngJ1tsXLLJ2x+0iQVNFV+32/htnDpSPUJL6MBc6YAAAA=",
    sources: [
      { width: 400, height: 601, avif: "/media/leopard-on-rock-400.avif", webp: "/media/leopard-on-rock-400.webp" },
      { width: 640, height: 961, avif: "/media/leopard-on-rock-640.avif", webp: "/media/leopard-on-rock-640.webp" },
      { width: 768, height: 1154, avif: "/media/leopard-on-rock-768.avif", webp: "/media/leopard-on-rock-768.webp" },
      { width: 900, height: 1352, avif: "/media/leopard-on-rock-900.avif", webp: "/media/leopard-on-rock-900.webp" },
    ],
    category: "forest",
    orientation: "portrait",
    fullBleedSafe: false,
  },
  {
    id: "melanistic-leopard",
    alt: "A melanistic leopard perched watchfully in the fork of a tree.",
    width: 900,
    height: 1352,
    avif: "/media/melanistic-leopard-900.avif",
    webp: "/media/melanistic-leopard-900.webp",
    jpg: "/media/melanistic-leopard-900.jpg",
    blur: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBgCdASoYACQAPulipk2pJaOiMAqpIB0JYwDC+B6NSqouO9dhOmqFgUtoZ5SqA7DIYgUNsMfwrAAA/r4BSQrllsQl94m0G8CY9U96d7p4eY4F4wcFLcFxJsQQWod+DUZQCHhJHeilcsUqHGofDB8QzPq9A3EAzHSr+aD4yC77w6ihQ4HS6kG0loL+AAAA",
    sources: [
      { width: 400, height: 601, avif: "/media/melanistic-leopard-400.avif", webp: "/media/melanistic-leopard-400.webp" },
      { width: 640, height: 961, avif: "/media/melanistic-leopard-640.avif", webp: "/media/melanistic-leopard-640.webp" },
      { width: 768, height: 1154, avif: "/media/melanistic-leopard-768.avif", webp: "/media/melanistic-leopard-768.webp" },
      { width: 900, height: 1352, avif: "/media/melanistic-leopard-900.avif", webp: "/media/melanistic-leopard-900.webp" },
    ],
    category: "forest",
    orientation: "portrait",
    fullBleedSafe: false,
  },
  {
    id: "forest-boardwalk-daylight",
    alt: "A timber boardwalk threading through forest, tangled vines framing the foreground.",
    width: 1440,
    height: 960,
    avif: "/media/forest-boardwalk-daylight-1440.avif",
    webp: "/media/forest-boardwalk-daylight-1440.webp",
    jpg: "/media/forest-boardwalk-daylight-1440.jpg",
    blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JYwCdABj3vnGLLCEc0LKAAP7ZXGEjeGXs0nUcqpXLJuKoK6SErWMpNhLdfCqnI3/0Ki0Sg6yo8AAA",
    sources: [
      { width: 400, height: 266, avif: "/media/forest-boardwalk-daylight-400.avif", webp: "/media/forest-boardwalk-daylight-400.webp" },
      { width: 640, height: 427, avif: "/media/forest-boardwalk-daylight-640.avif", webp: "/media/forest-boardwalk-daylight-640.webp" },
      { width: 768, height: 512, avif: "/media/forest-boardwalk-daylight-768.avif", webp: "/media/forest-boardwalk-daylight-768.webp" },
      { width: 960, height: 640, avif: "/media/forest-boardwalk-daylight-960.avif", webp: "/media/forest-boardwalk-daylight-960.webp" },
      { width: 1200, height: 800, avif: "/media/forest-boardwalk-daylight-1200.avif", webp: "/media/forest-boardwalk-daylight-1200.webp" },
      { width: 1440, height: 960, avif: "/media/forest-boardwalk-daylight-1440.avif", webp: "/media/forest-boardwalk-daylight-1440.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "forest-trail-canopy",
    alt: "A sunlit trail tunnelling beneath an arch of forest canopy.",
    width: 960,
    height: 640,
    avif: "/media/forest-trail-canopy-960.avif",
    webp: "/media/forest-trail-canopy-960.webp",
    jpg: "/media/forest-trail-canopy-960.jpg",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoYABAAPu1kq04ppaQiMAgBMB2JQBOgA6fuQN0yIogbhpAA/uv/FdC6EzlWK9xt53MqX6H+AQxxqqBbvIuWt/Y02ZBdbbIwwWrC1Fzoww99O5oGNrMZpRAA",
    sources: [
      { width: 400, height: 266, avif: "/media/forest-trail-canopy-400.avif", webp: "/media/forest-trail-canopy-400.webp" },
      { width: 640, height: 427, avif: "/media/forest-trail-canopy-640.avif", webp: "/media/forest-trail-canopy-640.webp" },
      { width: 768, height: 512, avif: "/media/forest-trail-canopy-768.avif", webp: "/media/forest-trail-canopy-768.webp" },
      { width: 960, height: 640, avif: "/media/forest-trail-canopy-960.avif", webp: "/media/forest-trail-canopy-960.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "tiger-crossing-track",
    alt: "A tiger crossing the track ahead of a safari jeep and its watching guests.",
    width: 541,
    height: 508,
    avif: "/media/tiger-crossing-track-541.avif",
    webp: "/media/tiger-crossing-track-541.webp",
    jpg: "/media/tiger-crossing-track-541.jpg",
    blur: "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADQBACdASoYABcAPu1qr1CppaQiqAqpMB2JZACdMuI20GCNgpQp/ccOzArpGfFQQAD+v6uRGyCUxtokL0XEXhYdat32o2TmAE6drMUo8w9ke7r48QXV9koPm/tjYBhyBG1xJPLC/rcxFwqyRhFM8hs2L4Cb40rmXGHqzig10RkTMQy4FCCmfFs5iq854MPwAAA=",
    sources: [
      { width: 400, height: 376, avif: "/media/tiger-crossing-track-400.avif", webp: "/media/tiger-crossing-track-400.webp" },
      { width: 541, height: 508, avif: "/media/tiger-crossing-track-541.avif", webp: "/media/tiger-crossing-track-541.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "mahua-vann-room",
    alt: "A mud-walled room at Mahua Vann with a tiled roof and forest views through open windows.",
    width: 1100,
    height: 734,
    avif: "/media/mahua-vann-room-1100.avif",
    webp: "/media/mahua-vann-room-1100.webp",
    jpg: "/media/mahua-vann-room-1100.jpg",
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoYABAAPu1iqk2ppaQiMAgBMB2JagCdMoR8eBxLXrye8UAaQMlnKAD9d6DI/JhKRlchBGRe+JhvwqPwhVG6Kg+Wahci59Flz2Rt98vJ/Aq3oBYL/BP1asuVOKwCB5bdzWXMYA6XXkk30f1UM7MQLk9FhoCfA3LAAAA=",
    sources: [
      { width: 400, height: 267, avif: "/media/mahua-vann-room-400.avif", webp: "/media/mahua-vann-room-400.webp" },
      { width: 640, height: 427, avif: "/media/mahua-vann-room-640.avif", webp: "/media/mahua-vann-room-640.webp" },
      { width: 768, height: 512, avif: "/media/mahua-vann-room-768.avif", webp: "/media/mahua-vann-room-768.webp" },
      { width: 960, height: 641, avif: "/media/mahua-vann-room-960.avif", webp: "/media/mahua-vann-room-960.webp" },
      { width: 1100, height: 734, avif: "/media/mahua-vann-room-1100.avif", webp: "/media/mahua-vann-room-1100.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "mahua-tola-suite",
    alt: "A family suite at Mahua Tola with a terracotta roof and jungle-print textiles.",
    width: 1100,
    height: 733,
    avif: "/media/mahua-tola-suite-1100.avif",
    webp: "/media/mahua-tola-suite-1100.webp",
    jpg: "/media/mahua-tola-suite-1100.jpg",
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOmUABoEf527P5+HbkXPQAA96SkbzbiauSn5mgt8lo7eSYAMna+DNsWwJ3MkvFQa3f3s8QJ7PriZ5e6PGCVfZGT8rn4qxaNKEvbQAA=",
    sources: [
      { width: 400, height: 267, avif: "/media/mahua-tola-suite-400.avif", webp: "/media/mahua-tola-suite-400.webp" },
      { width: 640, height: 426, avif: "/media/mahua-tola-suite-640.avif", webp: "/media/mahua-tola-suite-640.webp" },
      { width: 768, height: 512, avif: "/media/mahua-tola-suite-768.avif", webp: "/media/mahua-tola-suite-768.webp" },
      { width: 960, height: 640, avif: "/media/mahua-tola-suite-960.avif", webp: "/media/mahua-tola-suite-960.webp" },
      { width: 1100, height: 733, avif: "/media/mahua-tola-suite-1100.avif", webp: "/media/mahua-tola-suite-1100.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "guide-sunrise",
    alt: "A guide scanning the forest canopy with binoculars in the early sunrise light.",
    width: 1000,
    height: 666,
    avif: "/media/guide-sunrise-1000.avif",
    webp: "/media/guide-sunrise-1000.webp",
    jpg: "/media/guide-sunrise-1000.jpg",
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBACdASoYABAAPu1iqk2ppaQiMAgBMB2JQBhQBD4Q5qK089dcgx4fAAD+8c9ccRztEvJRpRBlhLnpdfFhPrxNfJLpcftp+PPiMHyXRDZc/kyLrxWzqAl+qw2pu/EgAAA=",
    sources: [
      { width: 400, height: 266, avif: "/media/guide-sunrise-400.avif", webp: "/media/guide-sunrise-400.webp" },
      { width: 640, height: 426, avif: "/media/guide-sunrise-640.avif", webp: "/media/guide-sunrise-640.webp" },
      { width: 768, height: 511, avif: "/media/guide-sunrise-768.avif", webp: "/media/guide-sunrise-768.webp" },
      { width: 960, height: 639, avif: "/media/guide-sunrise-960.avif", webp: "/media/guide-sunrise-960.webp" },
      { width: 1000, height: 666, avif: "/media/guide-sunrise-1000.avif", webp: "/media/guide-sunrise-1000.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "sound-healing",
    alt: "A sound healing session by candlelight, singing bowls set before a seated guest.",
    width: 1000,
    height: 666,
    avif: "/media/sound-healing-1000.avif",
    webp: "/media/sound-healing-1000.webp",
    jpg: "/media/sound-healing-1000.jpg",
    blur: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JZwDE2C0Hz28tYgAA/vAI/VmzOoP+FYpdGj/P6NR8QAAA",
    sources: [
      { width: 400, height: 266, avif: "/media/sound-healing-400.avif", webp: "/media/sound-healing-400.webp" },
      { width: 640, height: 426, avif: "/media/sound-healing-640.avif", webp: "/media/sound-healing-640.webp" },
      { width: 768, height: 511, avif: "/media/sound-healing-768.avif", webp: "/media/sound-healing-768.webp" },
      { width: 960, height: 639, avif: "/media/sound-healing-960.avif", webp: "/media/sound-healing-960.webp" },
      { width: 1000, height: 666, avif: "/media/sound-healing-1000.avif", webp: "/media/sound-healing-1000.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "room-hanging-chair-view",
    alt: "A mud-walled room opening onto a private balcony with a hanging cane chair among the trees.",
    width: 1440,
    height: 810,
    avif: "/media/room-hanging-chair-view-1440.avif",
    webp: "/media/room-hanging-chair-view-1440.webp",
    jpg: "/media/room-hanging-chair-view-1440.jpg",
    blur: "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoYAA0APu1iqk4ppaQiMAgBMB2JagCdAAxAUY1ryRS+AAD+0O8yRQQTeceERxqrm+9mgmAQuUZoYtRFhrZs7DvTYrHnp8IVCAI3XT8gafVCL5o5teOTlEfa/S5zbBbOTTAqEsNk5wsDuQ9qb/WG5WUU5eWoAAAA",
    sources: [
      { width: 400, height: 225, avif: "/media/room-hanging-chair-view-400.avif", webp: "/media/room-hanging-chair-view-400.webp" },
      { width: 640, height: 360, avif: "/media/room-hanging-chair-view-640.avif", webp: "/media/room-hanging-chair-view-640.webp" },
      { width: 768, height: 432, avif: "/media/room-hanging-chair-view-768.avif", webp: "/media/room-hanging-chair-view-768.webp" },
      { width: 960, height: 540, avif: "/media/room-hanging-chair-view-960.avif", webp: "/media/room-hanging-chair-view-960.webp" },
      { width: 1200, height: 675, avif: "/media/room-hanging-chair-view-1200.avif", webp: "/media/room-hanging-chair-view-1200.webp" },
      { width: 1440, height: 810, avif: "/media/room-hanging-chair-view-1440.avif", webp: "/media/room-hanging-chair-view-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "hanging-chair-forest-deck",
    alt: "A hanging cane chair on a private wooden deck above the forest stream.",
    width: 1440,
    height: 810,
    avif: "/media/hanging-chair-forest-deck-1440.avif",
    webp: "/media/hanging-chair-forest-deck-1440.webp",
    jpg: "/media/hanging-chair-forest-deck-1440.jpg",
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQAwCdASoYAA0APu1mq04ppaQiMAgBMB2JZgCdABRIqcsUo0/wAP6+QCluB0JhNiaHSbfL5/BG8p7AWPd7lBR7CCYQhp5uwk+bwubPsHiwUon/ejli0mI/C8Zq28CGuxDxOX0m6MFmAAAA",
    sources: [
      { width: 400, height: 225, avif: "/media/hanging-chair-forest-deck-400.avif", webp: "/media/hanging-chair-forest-deck-400.webp" },
      { width: 640, height: 360, avif: "/media/hanging-chair-forest-deck-640.avif", webp: "/media/hanging-chair-forest-deck-640.webp" },
      { width: 768, height: 432, avif: "/media/hanging-chair-forest-deck-768.avif", webp: "/media/hanging-chair-forest-deck-768.webp" },
      { width: 960, height: 540, avif: "/media/hanging-chair-forest-deck-960.avif", webp: "/media/hanging-chair-forest-deck-960.webp" },
      { width: 1200, height: 675, avif: "/media/hanging-chair-forest-deck-1200.avif", webp: "/media/hanging-chair-forest-deck-1200.webp" },
      { width: 1440, height: 810, avif: "/media/hanging-chair-forest-deck-1440.avif", webp: "/media/hanging-chair-forest-deck-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "bungalow-exterior-palms",
    alt: "A tiled-roof bungalow with young palms rising in front of its veranda.",
    width: 1440,
    height: 1080,
    avif: "/media/bungalow-exterior-palms-1440.avif",
    webp: "/media/bungalow-exterior-palms-1440.webp",
    jpg: "/media/bungalow-exterior-palms-1440.jpg",
    blur: "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoYABIAPu1qsFAppaUiqAqpMB2JQBjPgiO63UNDiZIPiJh3X5rdTVTjVgAA/u/EXhc2KLVun4J9hxRsNgQ5GdDqTlBfjc7zvKqu6iApq4oGrMTB4TmLf6FUqYrobFBZ0m2j6VgQKcksRHKdrkzfgAAA",
    sources: [
      { width: 400, height: 300, avif: "/media/bungalow-exterior-palms-400.avif", webp: "/media/bungalow-exterior-palms-400.webp" },
      { width: 640, height: 480, avif: "/media/bungalow-exterior-palms-640.avif", webp: "/media/bungalow-exterior-palms-640.webp" },
      { width: 768, height: 576, avif: "/media/bungalow-exterior-palms-768.avif", webp: "/media/bungalow-exterior-palms-768.webp" },
      { width: 960, height: 720, avif: "/media/bungalow-exterior-palms-960.avif", webp: "/media/bungalow-exterior-palms-960.webp" },
      { width: 1200, height: 900, avif: "/media/bungalow-exterior-palms-1200.avif", webp: "/media/bungalow-exterior-palms-1200.webp" },
      { width: 1440, height: 1080, avif: "/media/bungalow-exterior-palms-1440.avif", webp: "/media/bungalow-exterior-palms-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "suite-tiger-painting",
    alt: "A mud-walled suite with a painted cat's face above the bed and doors open to a forest deck.",
    width: 1440,
    height: 961,
    avif: "/media/suite-tiger-painting-1440.avif",
    webp: "/media/suite-tiger-painting-1440.webp",
    jpg: "/media/suite-tiger-painting-1440.jpg",
    blur: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JbACdMoACfdKg2MoldlQ3G7mUAP7RUPMxqtI868i+vDUF1W+cR5+pF5p/XnmsKVGwYVcYB52cXaIpHHPD4fa+p9buzDp9ETZS+Sm+UvoNEdetL5sv19kbuSBfjGrCjguI4luwJkluB7T4AQ/DUAAA",
    sources: [
      { width: 400, height: 267, avif: "/media/suite-tiger-painting-400.avif", webp: "/media/suite-tiger-painting-400.webp" },
      { width: 640, height: 427, avif: "/media/suite-tiger-painting-640.avif", webp: "/media/suite-tiger-painting-640.webp" },
      { width: 768, height: 512, avif: "/media/suite-tiger-painting-768.avif", webp: "/media/suite-tiger-painting-768.webp" },
      { width: 960, height: 641, avif: "/media/suite-tiger-painting-960.avif", webp: "/media/suite-tiger-painting-960.webp" },
      { width: 1200, height: 801, avif: "/media/suite-tiger-painting-1200.avif", webp: "/media/suite-tiger-painting-1200.webp" },
      { width: 1440, height: 961, avif: "/media/suite-tiger-painting-1440.avif", webp: "/media/suite-tiger-painting-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "room-open-to-bamboo",
    alt: "A room with a dark timber dado and terracotta beams, its doors open to a wall of bamboo.",
    width: 1440,
    height: 811,
    avif: "/media/room-open-to-bamboo-1440.avif",
    webp: "/media/room-open-to-bamboo-1440.webp",
    jpg: "/media/room-open-to-bamboo-1440.jpg",
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoYAA4APu1kqU2ppaOiMAgBMB2JbACxG1ABcABb7EFUJ0U9AAD2e96ctEv3+OTiFhwVw1DjBQV6Umo6HKnHcz683gYiVAIHDGuFt0p35+UVfh044PLtsCv0VxQcmXfizSbXoYGL+LPAKzOyAAA=",
    sources: [
      { width: 400, height: 225, avif: "/media/room-open-to-bamboo-400.avif", webp: "/media/room-open-to-bamboo-400.webp" },
      { width: 640, height: 360, avif: "/media/room-open-to-bamboo-640.avif", webp: "/media/room-open-to-bamboo-640.webp" },
      { width: 768, height: 432, avif: "/media/room-open-to-bamboo-768.avif", webp: "/media/room-open-to-bamboo-768.webp" },
      { width: 960, height: 540, avif: "/media/room-open-to-bamboo-960.avif", webp: "/media/room-open-to-bamboo-960.webp" },
      { width: 1200, height: 675, avif: "/media/room-open-to-bamboo-1200.avif", webp: "/media/room-open-to-bamboo-1200.webp" },
      { width: 1440, height: 811, avif: "/media/room-open-to-bamboo-1440.avif", webp: "/media/room-open-to-bamboo-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "lawn-picnic-golden-hour",
    alt: "Picnic tables and umbrellas set out on the lawn as the trees turn gold.",
    width: 1440,
    height: 960,
    avif: "/media/lawn-picnic-golden-hour-1440.avif",
    webp: "/media/lawn-picnic-golden-hour-1440.webp",
    jpg: "/media/lawn-picnic-golden-hour-1440.jpg",
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQAwCdASoYABAAPu1kq04ppaQiMAgBMB2JbACdABO6iI3erIfYAP6gbh6yQvbo9w7NjDcrT945xW+cicKyXLxb39cnR6fW2AW34uyBqYzo/7afAwdRzsnRyybZA9IUMuuYWwMXsxW4BBbMbVAAAA==",
    sources: [
      { width: 400, height: 266, avif: "/media/lawn-picnic-golden-hour-400.avif", webp: "/media/lawn-picnic-golden-hour-400.webp" },
      { width: 640, height: 427, avif: "/media/lawn-picnic-golden-hour-640.avif", webp: "/media/lawn-picnic-golden-hour-640.webp" },
      { width: 768, height: 512, avif: "/media/lawn-picnic-golden-hour-768.avif", webp: "/media/lawn-picnic-golden-hour-768.webp" },
      { width: 960, height: 640, avif: "/media/lawn-picnic-golden-hour-960.avif", webp: "/media/lawn-picnic-golden-hour-960.webp" },
      { width: 1200, height: 800, avif: "/media/lawn-picnic-golden-hour-1200.avif", webp: "/media/lawn-picnic-golden-hour-1200.webp" },
      { width: 1440, height: 960, avif: "/media/lawn-picnic-golden-hour-1440.avif", webp: "/media/lawn-picnic-golden-hour-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "hammocks-shade",
    alt: "Two rope hammocks slung between slender trees in dappled afternoon shade.",
    width: 1440,
    height: 810,
    avif: "/media/hammocks-shade-1440.avif",
    webp: "/media/hammocks-shade-1440.webp",
    jpg: "/media/hammocks-shade-1440.jpg",
    blur: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoYAA4APu1kq04ppaQiMAgBMB2JQBOgAcGh5K3HFWnOXgAA+xkkEUvp5L5KaWOQk9F/llX50C6Q4Vs+DAAX6jHMorkjLITOl9MgsTcF+pLkAAAA",
    sources: [
      { width: 400, height: 225, avif: "/media/hammocks-shade-400.avif", webp: "/media/hammocks-shade-400.webp" },
      { width: 640, height: 360, avif: "/media/hammocks-shade-640.avif", webp: "/media/hammocks-shade-640.webp" },
      { width: 768, height: 432, avif: "/media/hammocks-shade-768.avif", webp: "/media/hammocks-shade-768.webp" },
      { width: 960, height: 540, avif: "/media/hammocks-shade-960.avif", webp: "/media/hammocks-shade-960.webp" },
      { width: 1200, height: 675, avif: "/media/hammocks-shade-1200.avif", webp: "/media/hammocks-shade-1200.webp" },
      { width: 1440, height: 810, avif: "/media/hammocks-shade-1440.avif", webp: "/media/hammocks-shade-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "garden-path-lodge",
    alt: "A stone path through palms and bamboo towards the lodge's reception rooms.",
    width: 1440,
    height: 1080,
    avif: "/media/garden-path-lodge-1440.avif",
    webp: "/media/garden-path-lodge-1440.webp",
    jpg: "/media/garden-path-lodge-1440.jpg",
    blur: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoYABIAPu1srVEppaQiqAqpMB2JQBdgAcSSL5qqrtvLzFwlk1YbtX0AAP5JgquRcDh83vkOR3nPJLoxjnnEcyDTM6fmpboKi4vTtybVten3Row0FVEPHsQGN/D7PTbiy48HYdgR4+POLIliwd7dsexpbQAAAA==",
    sources: [
      { width: 400, height: 300, avif: "/media/garden-path-lodge-400.avif", webp: "/media/garden-path-lodge-400.webp" },
      { width: 640, height: 480, avif: "/media/garden-path-lodge-640.avif", webp: "/media/garden-path-lodge-640.webp" },
      { width: 768, height: 576, avif: "/media/garden-path-lodge-768.avif", webp: "/media/garden-path-lodge-768.webp" },
      { width: 960, height: 720, avif: "/media/garden-path-lodge-960.avif", webp: "/media/garden-path-lodge-960.webp" },
      { width: 1200, height: 900, avif: "/media/garden-path-lodge-1200.avif", webp: "/media/garden-path-lodge-1200.webp" },
      { width: 1440, height: 1080, avif: "/media/garden-path-lodge-1440.avif", webp: "/media/garden-path-lodge-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "pool-daylight-forest",
    alt: "The pool by daylight, banana leaves and forest closing around the water.",
    width: 1163,
    height: 510,
    avif: "/media/pool-daylight-forest-1163.avif",
    webp: "/media/pool-daylight-forest-1163.webp",
    jpg: "/media/pool-daylight-forest-1163.jpg",
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoYAAsAPu1kqk4ppaQiMAgBMB2JbACdMoRwACfGRdxx9mHhuYAA/j2lXJHOoW8D4kgo1Y8q9Bi8EwLmuThPjlf8DRH8bd7JZLToEQ5A6Njg37JxeI4r5QwXZn9QYfsgcqyn5DurAAA=",
    sources: [
      { width: 400, height: 175, avif: "/media/pool-daylight-forest-400.avif", webp: "/media/pool-daylight-forest-400.webp" },
      { width: 640, height: 281, avif: "/media/pool-daylight-forest-640.avif", webp: "/media/pool-daylight-forest-640.webp" },
      { width: 768, height: 337, avif: "/media/pool-daylight-forest-768.avif", webp: "/media/pool-daylight-forest-768.webp" },
      { width: 960, height: 421, avif: "/media/pool-daylight-forest-960.avif", webp: "/media/pool-daylight-forest-960.webp" },
      { width: 1163, height: 510, avif: "/media/pool-daylight-forest-1163.avif", webp: "/media/pool-daylight-forest-1163.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "potters-hands",
    alt: "A potter's clay-covered hands shaping a vessel on the wheel.",
    width: 700,
    height: 466,
    avif: "/media/potters-hands-700.avif",
    webp: "/media/potters-hands-700.webp",
    jpg: "/media/potters-hands-700.jpg",
    blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JQBYdgoY3gAyMHk0WAAAA/oKFy49u4d1+q02aCHk7m6Rky//8leOIzyuBnkKra8gLcIAA",
    sources: [
      { width: 400, height: 266, avif: "/media/potters-hands-400.avif", webp: "/media/potters-hands-400.webp" },
      { width: 640, height: 426, avif: "/media/potters-hands-640.avif", webp: "/media/potters-hands-640.webp" },
      { width: 700, height: 466, avif: "/media/potters-hands-700.avif", webp: "/media/potters-hands-700.webp" },
    ],
    category: "details",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "petal-bowl-map",
    alt: "Rose petals afloat in a stone bowl before a lantern-lit forest map.",
    width: 700,
    height: 1050,
    avif: "/media/petal-bowl-map-700.avif",
    webp: "/media/petal-bowl-map-700.webp",
    jpg: "/media/petal-bowl-map-700.jpg",
    blur: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQBQCdASoYACQAPuVipk2pJaOiNVgIASAciWUAxchFbWL8qUiaVBwfy/Q6sjSdQm16S4Ye4AD+9D+18mBHedY35SK5Wus3STWKbs6dqEt4j28ojz4978tZSQmP7+EuadqCpBWUopJH+AAA",
    sources: [
      { width: 400, height: 600, avif: "/media/petal-bowl-map-400.avif", webp: "/media/petal-bowl-map-400.webp" },
      { width: 640, height: 960, avif: "/media/petal-bowl-map-640.avif", webp: "/media/petal-bowl-map-640.webp" },
      { width: 700, height: 1050, avif: "/media/petal-bowl-map-700.avif", webp: "/media/petal-bowl-map-700.webp" },
    ],
    category: "details",
    orientation: "portrait",
    fullBleedSafe: false,
  },
  {
    id: "forest-shrine-incense",
    alt: "Incense smoke rising from a small forest shrine beneath a hanging lamp.",
    width: 700,
    height: 1050,
    avif: "/media/forest-shrine-incense-700.avif",
    webp: "/media/forest-shrine-incense-700.webp",
    jpg: "/media/forest-shrine-incense-700.jpg",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoYACQAPuVeqE2pJSiiMBqtUSAciWcAyngdkBIRVJdQu0eX5fAA/u9f29auuOnOiB/ryG3fZ/nc/LXLgqscEADSKcW4NSuKgxsuJvb7hoNOGozSGW2gAAAA",
    sources: [
      { width: 400, height: 600, avif: "/media/forest-shrine-incense-400.avif", webp: "/media/forest-shrine-incense-400.webp" },
      { width: 640, height: 960, avif: "/media/forest-shrine-incense-640.avif", webp: "/media/forest-shrine-incense-640.webp" },
      { width: 700, height: 1050, avif: "/media/forest-shrine-incense-700.avif", webp: "/media/forest-shrine-incense-700.webp" },
    ],
    category: "details",
    orientation: "portrait",
    fullBleedSafe: false,
  },
  {
    id: "lily-pond-fountain",
    alt: "Water lilies crowding a stone fountain, the lawn stretching out beyond.",
    width: 1080,
    height: 1080,
    avif: "/media/lily-pond-fountain-1080.avif",
    webp: "/media/lily-pond-fountain-1080.webp",
    jpg: "/media/lily-pond-fountain-1080.jpg",
    blur: "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBACdASoYABgAPu1qsFAppaUiqAqpMB2JZACdM0xBQ64js20juoAkSo3bggw4TEAA+kFMpbBLZQFlx01GOVqL1IHVuKjPti2KWLRZmwrXNfWNJ4icF9WLnDMRhU9dbJkxFYawQeManWDxD2p6ADFbenrI7gqmj1RxZxIzWuVS3R1RkyyRo6HE9lii6k2MAAA=",
    sources: [
      { width: 400, height: 400, avif: "/media/lily-pond-fountain-400.avif", webp: "/media/lily-pond-fountain-400.webp" },
      { width: 640, height: 640, avif: "/media/lily-pond-fountain-640.avif", webp: "/media/lily-pond-fountain-640.webp" },
      { width: 768, height: 768, avif: "/media/lily-pond-fountain-768.avif", webp: "/media/lily-pond-fountain-768.webp" },
      { width: 960, height: 960, avif: "/media/lily-pond-fountain-960.avif", webp: "/media/lily-pond-fountain-960.webp" },
      { width: 1080, height: 1080, avif: "/media/lily-pond-fountain-1080.avif", webp: "/media/lily-pond-fountain-1080.webp" },
    ],
    category: "details",
    orientation: "square",
    fullBleedSafe: false,
  },
  {
    id: "geese-garden-pond",
    alt: "A family of geese paddling across a garden pond beneath overhanging leaves.",
    width: 1440,
    height: 960,
    avif: "/media/geese-garden-pond-1440.avif",
    webp: "/media/geese-garden-pond-1440.webp",
    jpg: "/media/geese-garden-pond-1440.jpg",
    blur: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZgCsABIaLuL0lFYQ9KDPgAD+71mdDq+ABItYbCj1Tocng64sOCKTrskTBL6ZsuAzrKy9iGodbLXYvDhCh10LN8FA+iGaAMVY4w8SKU3Z9W/tt8fkAA==",
    sources: [
      { width: 400, height: 266, avif: "/media/geese-garden-pond-400.avif", webp: "/media/geese-garden-pond-400.webp" },
      { width: 640, height: 427, avif: "/media/geese-garden-pond-640.avif", webp: "/media/geese-garden-pond-640.webp" },
      { width: 768, height: 512, avif: "/media/geese-garden-pond-768.avif", webp: "/media/geese-garden-pond-768.webp" },
      { width: 960, height: 640, avif: "/media/geese-garden-pond-960.avif", webp: "/media/geese-garden-pond-960.webp" },
      { width: 1200, height: 800, avif: "/media/geese-garden-pond-1200.avif", webp: "/media/geese-garden-pond-1200.webp" },
      { width: 1440, height: 960, avif: "/media/geese-garden-pond-1440.avif", webp: "/media/geese-garden-pond-1440.webp" },
    ],
    category: "details",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "vann-hero",
    alt: "The entrance court at Mahua Vann — brass pots, lanterns, and a bowl of petals at the dining-hall doors.",
    width: 1440,
    height: 960,
    avif: "/media/vann-hero-1440.avif",
    webp: "/media/vann-hero-1440.webp",
    jpg: "/media/vann-hero-1440.jpg",
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JbACdMoMYLwzAa0+McAb9CaofAAD+0Pgdmw1w8h8hvDl2RcdkarApVwRb8ymnZI79Fh9T1LgeHzPOuRuGd+mQUFR6rD/fQZpIWlsSrZlKDfKbgEH4OP3D8oTucynws3urOpboAAA=",
    sources: [
      { width: 400, height: 266, avif: "/media/vann-hero-400.avif", webp: "/media/vann-hero-400.webp" },
      { width: 640, height: 427, avif: "/media/vann-hero-640.avif", webp: "/media/vann-hero-640.webp" },
      { width: 768, height: 512, avif: "/media/vann-hero-768.avif", webp: "/media/vann-hero-768.webp" },
      { width: 960, height: 640, avif: "/media/vann-hero-960.avif", webp: "/media/vann-hero-960.webp" },
      { width: 1200, height: 800, avif: "/media/vann-hero-1200.avif", webp: "/media/vann-hero-1200.webp" },
      { width: 1440, height: 960, avif: "/media/vann-hero-1440.avif", webp: "/media/vann-hero-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "vann-room-deluxe",
    alt: "A Deluxe room at Mahua Vann, garden and jungle view.",
    width: 1163,
    height: 508,
    avif: "/media/vann-room-deluxe-1163.avif",
    webp: "/media/vann-room-deluxe-1163.webp",
    jpg: "/media/vann-room-deluxe-1163.jpg",
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoYAAoAPu1kqU2ppaQiMAgBMB2JagCdL1yBmMX/iBco7MYzwAD9O3G+wwpmLzus7HSFBP7Dyriq5Z7rb1jgvxsGjWXjcK569XABfUnjOehSWKeeOpA5Inb4BgTtxUADQAA=",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-room-deluxe-400.avif", webp: "/media/vann-room-deluxe-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-room-deluxe-640.avif", webp: "/media/vann-room-deluxe-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-room-deluxe-768.avif", webp: "/media/vann-room-deluxe-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-room-deluxe-960.avif", webp: "/media/vann-room-deluxe-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-room-deluxe-1163.avif", webp: "/media/vann-room-deluxe-1163.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-safari",
    alt: "An open safari vehicle on a morning game drive at Pench.",
    width: 1163,
    height: 508,
    avif: "/media/vann-safari-1163.avif",
    webp: "/media/vann-safari-1163.webp",
    jpg: "/media/vann-safari-1163.jpg",
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoYAAoAPu1kqU4ppaOiMAgBMB2JaACdLwABo02yezWnuZmAAP7bXBwNL1yWDOKdB6Lq847uInzpjzD6gijyL5IZYuaIu6k0hXauidzK1GYpNWK3JNwmFPDMAAA=",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-safari-400.avif", webp: "/media/vann-safari-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-safari-640.avif", webp: "/media/vann-safari-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-safari-768.avif", webp: "/media/vann-safari-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-safari-960.avif", webp: "/media/vann-safari-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-safari-1163.avif", webp: "/media/vann-safari-1163.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-kohka-lake",
    alt: "Kohka Lake near Mahua Vann, still water at the forest's edge.",
    width: 1163,
    height: 508,
    avif: "/media/vann-kohka-lake-1163.avif",
    webp: "/media/vann-kohka-lake-1163.webp",
    jpg: "/media/vann-kohka-lake-1163.jpg",
    blur: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoYAAoAPu1kqk2ppaQiMAgBMB2JZACsAGjp0mRHSRv90sAA/vYzx1B6B9igAw2rvC4DiAnVTNYGjnDFOsfPsF6INsQcNPyPGWAAAA==",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-kohka-lake-400.avif", webp: "/media/vann-kohka-lake-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-kohka-lake-640.avif", webp: "/media/vann-kohka-lake-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-kohka-lake-768.avif", webp: "/media/vann-kohka-lake-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-kohka-lake-960.avif", webp: "/media/vann-kohka-lake-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-kohka-lake-1163.avif", webp: "/media/vann-kohka-lake-1163.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-potters-village",
    alt: "Terracotta and blackened clay pots drying in the sun at Pachdhar, the potters' village near Pench.",
    width: 1163,
    height: 508,
    avif: "/media/vann-potters-village-1163.avif",
    webp: "/media/vann-potters-village-1163.webp",
    jpg: "/media/vann-potters-village-1163.jpg",
    blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoYAAoAPu1oqk6ppiQiMAgBMB2JYgCdMoADSzBcOc+r+YiDgl2AAP57bam+pxKgwXR8nP8ATKOSCWBnqfNbeVsBZBS30Pa6cxLsnNlHoIcZyLJpilwjUHgA",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-potters-village-400.avif", webp: "/media/vann-potters-village-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-potters-village-640.avif", webp: "/media/vann-potters-village-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-potters-village-768.avif", webp: "/media/vann-potters-village-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-potters-village-960.avif", webp: "/media/vann-potters-village-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-potters-village-1163.avif", webp: "/media/vann-potters-village-1163.webp" },
    ],
    category: "details",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-dining",
    alt: "A table laid at Mahua Vann, seasonal dishes under the open sky.",
    width: 1163,
    height: 508,
    avif: "/media/vann-dining-1163.avif",
    webp: "/media/vann-dining-1163.webp",
    jpg: "/media/vann-dining-1163.jpg",
    blur: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwBACdASoYAAoAPu1kqk4ppaQiMAgBMB2JaACdMoADQvaEbN4p7GFAAKAA/qa4oAFlBPwkpquCq8vmPdYj2IJmq6kyBySyNKGVpFRrVE0YhQqtt1CovHyc7NO0Q1Vv7RAAAA==",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-dining-400.avif", webp: "/media/vann-dining-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-dining-640.avif", webp: "/media/vann-dining-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-dining-768.avif", webp: "/media/vann-dining-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-dining-960.avif", webp: "/media/vann-dining-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-dining-1163.avif", webp: "/media/vann-dining-1163.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-bird-watching",
    alt: "Birdwatching in Mahua Vann's private eco park.",
    width: 1163,
    height: 508,
    avif: "/media/vann-bird-watching-1163.avif",
    webp: "/media/vann-bird-watching-1163.webp",
    jpg: "/media/vann-bird-watching-1163.jpg",
    blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoYAAoAPu1iqU2ppaOiMAgBMB2JQBdmUAAp+MUBIUsakAAA/suYksYuiR2Ii35yQw5jyNB71bstUxoVadz+LJa5oqK0tNOue33ntKwA",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-bird-watching-400.avif", webp: "/media/vann-bird-watching-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-bird-watching-640.avif", webp: "/media/vann-bird-watching-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-bird-watching-768.avif", webp: "/media/vann-bird-watching-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-bird-watching-960.avif", webp: "/media/vann-bird-watching-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-bird-watching-1163.avif", webp: "/media/vann-bird-watching-1163.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-evening",
    alt: "An open-air wildlife documentary in Mahua Vann's courtyard after dinner.",
    width: 1163,
    height: 508,
    avif: "/media/vann-evening-1163.avif",
    webp: "/media/vann-evening-1163.webp",
    jpg: "/media/vann-evening-1163.jpg",
    blur: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoYAAoAPu1kqU2ppaQiMAgBMB2JQBOmUABffsDOmGya8eAA/uxPxrLI9NptxoYcHXpdwPg8CVVh5Y9+u+DOlCEH3rsdbwW0E4l2lsej2AA=",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-evening-400.avif", webp: "/media/vann-evening-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-evening-640.avif", webp: "/media/vann-evening-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-evening-768.avif", webp: "/media/vann-evening-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-evening-960.avif", webp: "/media/vann-evening-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-evening-1163.avif", webp: "/media/vann-evening-1163.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-tiger",
    alt: "A tiger pausing between sal trunks in Pench.",
    width: 1163,
    height: 508,
    avif: "/media/vann-tiger-1163.avif",
    webp: "/media/vann-tiger-1163.webp",
    jpg: "/media/vann-tiger-1163.jpg",
    blur: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwBACdASoYAAoAPu1kqk4ppaQiMAgBMB2JQBOmUABOiA4/xQqzJysmfAAA/rl2DQMuXGp7+llf2K8lN1Qr8uHZ/XyHZgd5g+8L0qM9qsAAAA==",
    sources: [
      { width: 400, height: 175, avif: "/media/vann-tiger-400.avif", webp: "/media/vann-tiger-400.webp" },
      { width: 640, height: 280, avif: "/media/vann-tiger-640.avif", webp: "/media/vann-tiger-640.webp" },
      { width: 768, height: 335, avif: "/media/vann-tiger-768.avif", webp: "/media/vann-tiger-768.webp" },
      { width: 960, height: 419, avif: "/media/vann-tiger-960.avif", webp: "/media/vann-tiger-960.webp" },
      { width: 1163, height: 508, avif: "/media/vann-tiger-1163.avif", webp: "/media/vann-tiger-1163.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-pool",
    alt: "Mahua Vann's pool under the trees, late-afternoon sun through the canopy.",
    width: 1440,
    height: 960,
    avif: "/media/vann-pool-1440.avif",
    webp: "/media/vann-pool-1440.webp",
    jpg: "/media/vann-pool-1440.jpg",
    blur: "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoYABAAPu1kqU4ppaOiMAgBMB2JQAAITuDXtKpyzVAiboMAAP59ZnCzsUpiki/0L+RCGJfefIT+I7ht4/JJit5R/8wbeNY86D6XduCrBGlwwKecSybG1hgO/c1YX0q8qRYRhZhYqMLSE9zpA8AAAA==",
    sources: [
      { width: 400, height: 266, avif: "/media/vann-pool-400.avif", webp: "/media/vann-pool-400.webp" },
      { width: 640, height: 427, avif: "/media/vann-pool-640.avif", webp: "/media/vann-pool-640.webp" },
      { width: 768, height: 512, avif: "/media/vann-pool-768.avif", webp: "/media/vann-pool-768.webp" },
      { width: 960, height: 640, avif: "/media/vann-pool-960.avif", webp: "/media/vann-pool-960.webp" },
      { width: 1200, height: 800, avif: "/media/vann-pool-1200.avif", webp: "/media/vann-pool-1200.webp" },
      { width: 1440, height: 960, avif: "/media/vann-pool-1440.avif", webp: "/media/vann-pool-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "tola-hero",
    alt: "Mahua Tola across its lily pond at dusk, the lodge lit under the trees.",
    width: 1440,
    height: 960,
    avif: "/media/tola-hero-1440.avif",
    webp: "/media/tola-hero-1440.webp",
    jpg: "/media/tola-hero-1440.jpg",
    blur: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JYwAAM7YLjXWo6RpkQQAA/k3wsLrX8MmP7O8FGRz1vWy8kzfImwpxZEOE9Wvbp5JlZwmlqBYoP9O300yWoTdHr+55XWC8YEwCj5YCAIAAAA==",
    sources: [
      { width: 400, height: 266, avif: "/media/tola-hero-400.avif", webp: "/media/tola-hero-400.webp" },
      { width: 640, height: 427, avif: "/media/tola-hero-640.avif", webp: "/media/tola-hero-640.webp" },
      { width: 768, height: 512, avif: "/media/tola-hero-768.avif", webp: "/media/tola-hero-768.webp" },
      { width: 960, height: 640, avif: "/media/tola-hero-960.avif", webp: "/media/tola-hero-960.webp" },
      { width: 1200, height: 800, avif: "/media/tola-hero-1200.avif", webp: "/media/tola-hero-1200.webp" },
      { width: 1440, height: 960, avif: "/media/tola-hero-1440.avif", webp: "/media/tola-hero-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "tola-candlelit-dinner",
    alt: "A candlelit dinner for two laid beside Mahua Tola's pool at night.",
    width: 1440,
    height: 961,
    avif: "/media/tola-candlelit-dinner-1440.avif",
    webp: "/media/tola-candlelit-dinner-1440.webp",
    jpg: "/media/tola-candlelit-dinner-1440.jpg",
    blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoYABAAPu1mqk2ppaQiMAgBMB2JZwDLLCHfl8pRbueWZAAA/vQdj7lKI/240c72GLIbJUpNVWeWL9iZwDNWTsKK4N6Jt6AA",
    sources: [
      { width: 400, height: 267, avif: "/media/tola-candlelit-dinner-400.avif", webp: "/media/tola-candlelit-dinner-400.webp" },
      { width: 640, height: 427, avif: "/media/tola-candlelit-dinner-640.avif", webp: "/media/tola-candlelit-dinner-640.webp" },
      { width: 768, height: 512, avif: "/media/tola-candlelit-dinner-768.avif", webp: "/media/tola-candlelit-dinner-768.webp" },
      { width: 960, height: 641, avif: "/media/tola-candlelit-dinner-960.avif", webp: "/media/tola-candlelit-dinner-960.webp" },
      { width: 1200, height: 801, avif: "/media/tola-candlelit-dinner-1200.avif", webp: "/media/tola-candlelit-dinner-1200.webp" },
      { width: 1440, height: 961, avif: "/media/tola-candlelit-dinner-1440.avif", webp: "/media/tola-candlelit-dinner-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "tola-room-family",
    alt: "The Family Suite at Mahua Tola — terracotta beams and a Gond painting over the bed.",
    width: 1440,
    height: 2160,
    avif: "/media/tola-room-family-1440.avif",
    webp: "/media/tola-room-family-1440.webp",
    jpg: "/media/tola-room-family-1440.jpg",
    blur: "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACwBgCdASoYACQAPu1erE4ppKSiMBqqqTAdiUAVgAL7+rznQt/8NV3D/SUxKLDjTnHHpaKsGOwtsdm/nlerAAD+6QKPumBGHMS5x8RDdf0XZvE/i3giJQ54Xq0beHJCqBnfIULhcxai5adVPmyiKqib7pCCA3cDDqnaKuDMVopMDHxkjQFsETEbcUAalkyn0TPzapQe1ZYhjykTsdwiKUOHK1OVV37w4r0IG8Hl5OxKH0AA",
    sources: [
      { width: 400, height: 600, avif: "/media/tola-room-family-400.avif", webp: "/media/tola-room-family-400.webp" },
      { width: 640, height: 960, avif: "/media/tola-room-family-640.avif", webp: "/media/tola-room-family-640.webp" },
      { width: 768, height: 1152, avif: "/media/tola-room-family-768.avif", webp: "/media/tola-room-family-768.webp" },
      { width: 960, height: 1440, avif: "/media/tola-room-family-960.avif", webp: "/media/tola-room-family-960.webp" },
      { width: 1200, height: 1800, avif: "/media/tola-room-family-1200.avif", webp: "/media/tola-room-family-1200.webp" },
      { width: 1440, height: 2160, avif: "/media/tola-room-family-1440.avif", webp: "/media/tola-room-family-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "portrait",
    fullBleedSafe: false,
  },
  {
    id: "tola-room-deluxe",
    alt: "A Deluxe room at Mahua Tola, forest view.",
    width: 1163,
    height: 508,
    avif: "/media/tola-room-deluxe-1163.avif",
    webp: "/media/tola-room-deluxe-1163.webp",
    jpg: "/media/tola-room-deluxe-1163.jpg",
    blur: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoYAAoAPu1iqU2ppaOiMAgBMB2JbACdMoR3ABwlKmSK2VqAUOAA/uf7akq9BeWPQhR8/+UCDwPkjteAIxoOkLS/4Om01w2dFv9SCVKnFe4FoE7kVY/Td0VRtIA3/B7wiSMMZkKayfcSPJAAAAA=",
    sources: [
      { width: 400, height: 175, avif: "/media/tola-room-deluxe-400.avif", webp: "/media/tola-room-deluxe-400.webp" },
      { width: 640, height: 280, avif: "/media/tola-room-deluxe-640.avif", webp: "/media/tola-room-deluxe-640.webp" },
      { width: 768, height: 335, avif: "/media/tola-room-deluxe-768.avif", webp: "/media/tola-room-deluxe-768.webp" },
      { width: 960, height: 419, avif: "/media/tola-room-deluxe-960.avif", webp: "/media/tola-room-deluxe-960.webp" },
      { width: 1163, height: 508, avif: "/media/tola-room-deluxe-1163.avif", webp: "/media/tola-room-deluxe-1163.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "tola-room-suite",
    alt: "A Suite room at Mahua Tola, forest view.",
    width: 1163,
    height: 508,
    avif: "/media/tola-room-suite-1163.avif",
    webp: "/media/tola-room-suite-1163.webp",
    jpg: "/media/tola-room-suite-1163.jpg",
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoYAAoAPu1kqk4ppaQiMAgBMB2JYgCdMoR8eB0xM5Ly5tXDZ4WYAP6vm1IcW4jualWcTkMNElyhQTNam25zW0bqcvRfM9RnhhE1HU4O2WxenBZZBZmho0CKAAA=",
    sources: [
      { width: 400, height: 175, avif: "/media/tola-room-suite-400.avif", webp: "/media/tola-room-suite-400.webp" },
      { width: 640, height: 280, avif: "/media/tola-room-suite-640.avif", webp: "/media/tola-room-suite-640.webp" },
      { width: 768, height: 335, avif: "/media/tola-room-suite-768.avif", webp: "/media/tola-room-suite-768.webp" },
      { width: 960, height: 419, avif: "/media/tola-room-suite-960.avif", webp: "/media/tola-room-suite-960.webp" },
      { width: 1163, height: 508, avif: "/media/tola-room-suite-1163.avif", webp: "/media/tola-room-suite-1163.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "tola-room-camping",
    alt: "The camping hut at Mahua Tola, forest view.",
    width: 1163,
    height: 508,
    avif: "/media/tola-room-camping-1163.avif",
    webp: "/media/tola-room-camping-1163.webp",
    jpg: "/media/tola-room-camping-1163.jpg",
    blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwBACdASoYAAoAPu1iqU2ppaOiMAgBMB2JaACdMoRwACjhR9G7PtvOI4s3wADNtJK5G1upNcZRH4oGe9Pp0xCD33R/D4ubGBcgjMWvSXhoSd1wJDIypbFEfRovqI4J7iLc15F8AAA=",
    sources: [
      { width: 400, height: 175, avif: "/media/tola-room-camping-400.avif", webp: "/media/tola-room-camping-400.webp" },
      { width: 640, height: 280, avif: "/media/tola-room-camping-640.avif", webp: "/media/tola-room-camping-640.webp" },
      { width: 768, height: 335, avif: "/media/tola-room-camping-768.avif", webp: "/media/tola-room-camping-768.webp" },
      { width: 960, height: 419, avif: "/media/tola-room-camping-960.avif", webp: "/media/tola-room-camping-960.webp" },
      { width: 1163, height: 508, avif: "/media/tola-room-camping-1163.avif", webp: "/media/tola-room-camping-1163.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "tola-tiger-safari",
    alt: "Three tigers at rest in the shade at Tadoba-Andhari Tiger Reserve.",
    width: 1163,
    height: 508,
    avif: "/media/tola-tiger-safari-1163.avif",
    webp: "/media/tola-tiger-safari-1163.webp",
    jpg: "/media/tola-tiger-safari-1163.jpg",
    blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoYAAoAPu1iqk4ppaQiMAgBMB2JZACsABtjfGiBdih2mAD+p6RZzItcpr1/grzLTzXjCa16daRbKryxDEIKt9FYYtTZTJ5fulNwaMAA",
    sources: [
      { width: 400, height: 175, avif: "/media/tola-tiger-safari-400.avif", webp: "/media/tola-tiger-safari-400.webp" },
      { width: 640, height: 280, avif: "/media/tola-tiger-safari-640.avif", webp: "/media/tola-tiger-safari-640.webp" },
      { width: 768, height: 335, avif: "/media/tola-tiger-safari-768.avif", webp: "/media/tola-tiger-safari-768.webp" },
      { width: 960, height: 419, avif: "/media/tola-tiger-safari-960.avif", webp: "/media/tola-tiger-safari-960.webp" },
      { width: 1163, height: 508, avif: "/media/tola-tiger-safari-1163.avif", webp: "/media/tola-tiger-safari-1163.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "tola-river-walk",
    alt: "The Hattinala river near Mahua Tola.",
    width: 1163,
    height: 508,
    avif: "/media/tola-river-walk-1163.avif",
    webp: "/media/tola-river-walk-1163.webp",
    jpg: "/media/tola-river-walk-1163.jpg",
    blur: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAwCdASoYAAoAPu1iqU2ppaQiMAgBMB2JZWQQU0AUGQAA/uvwj75AshKAIV17fVT00Z8Vm6rGBOdAVa3eG1AA",
    sources: [
      { width: 400, height: 175, avif: "/media/tola-river-walk-400.avif", webp: "/media/tola-river-walk-400.webp" },
      { width: 640, height: 280, avif: "/media/tola-river-walk-640.avif", webp: "/media/tola-river-walk-640.webp" },
      { width: 768, height: 335, avif: "/media/tola-river-walk-768.avif", webp: "/media/tola-river-walk-768.webp" },
      { width: 960, height: 419, avif: "/media/tola-river-walk-960.avif", webp: "/media/tola-river-walk-960.webp" },
      { width: 1163, height: 508, avif: "/media/tola-river-walk-1163.avif", webp: "/media/tola-river-walk-1163.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "tola-experiences",
    alt: "Rope hammocks slung between the trees at Mahua Tola.",
    width: 1163,
    height: 508,
    avif: "/media/tola-experiences-1163.avif",
    webp: "/media/tola-experiences-1163.webp",
    jpg: "/media/tola-experiences-1163.jpg",
    blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoYAAoAPu1kqk4ppaQiMAgBMB2JQBOgBC1m8+C8bwDV/OAA/tERtkRYP0HbVFPvicyNzeDjHtCAgjysRURJ6XAIFY0g+NQA",
    sources: [
      { width: 400, height: 175, avif: "/media/tola-experiences-400.avif", webp: "/media/tola-experiences-400.webp" },
      { width: 640, height: 280, avif: "/media/tola-experiences-640.avif", webp: "/media/tola-experiences-640.webp" },
      { width: 768, height: 335, avif: "/media/tola-experiences-768.avif", webp: "/media/tola-experiences-768.webp" },
      { width: 960, height: 419, avif: "/media/tola-experiences-960.avif", webp: "/media/tola-experiences-960.webp" },
      { width: 1163, height: 508, avif: "/media/tola-experiences-1163.avif", webp: "/media/tola-experiences-1163.webp" },
    ],
    category: "forest",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "tola-dining",
    alt: "The dining hall at Mahua Tola, tables laid under wicker pendant lamps.",
    width: 1440,
    height: 960,
    avif: "/media/tola-dining-1440.avif",
    webp: "/media/tola-dining-1440.webp",
    jpg: "/media/tola-dining-1440.jpg",
    blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBACdASoYABAAPu1kqU4ppaOiMAgBMB2JQBOmUABbe0Otb/fYOAChf0AA/kf3aFSPIMlWyGb09Shg5mnml6ScONRaWBMqaQ9tQDY8eT+qzEmQMECzihmYlWzO+EPPRzX7C/WPkcgGN4sg2MBYLuvwE5B0GiAAAAA=",
    sources: [
      { width: 400, height: 266, avif: "/media/tola-dining-400.avif", webp: "/media/tola-dining-400.webp" },
      { width: 640, height: 427, avif: "/media/tola-dining-640.avif", webp: "/media/tola-dining-640.webp" },
      { width: 768, height: 512, avif: "/media/tola-dining-768.avif", webp: "/media/tola-dining-768.webp" },
      { width: 960, height: 640, avif: "/media/tola-dining-960.avif", webp: "/media/tola-dining-960.webp" },
      { width: 1200, height: 800, avif: "/media/tola-dining-1200.avif", webp: "/media/tola-dining-1200.webp" },
      { width: 1440, height: 960, avif: "/media/tola-dining-1440.avif", webp: "/media/tola-dining-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "tola-guest-word",
    alt: "An accommodation block at Mahua Tola, dusk light through the bamboo.",
    width: 1440,
    height: 960,
    avif: "/media/tola-guest-word-1440.avif",
    webp: "/media/tola-guest-word-1440.webp",
    jpg: "/media/tola-guest-word-1440.jpg",
    blur: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoYABAAPu1kqk4ppaQiMAgBMB2JYgCsMoADUEHccgywXVXiKL0AAP2/jvSfWC/6wnwpN53DFZvOQKb29UApp8JTKFitKc9Q0DXk8eIyyvi3LHzJW6E2+/FcAAA=",
    sources: [
      { width: 400, height: 266, avif: "/media/tola-guest-word-400.avif", webp: "/media/tola-guest-word-400.webp" },
      { width: 640, height: 427, avif: "/media/tola-guest-word-640.avif", webp: "/media/tola-guest-word-640.webp" },
      { width: 768, height: 512, avif: "/media/tola-guest-word-768.avif", webp: "/media/tola-guest-word-768.webp" },
      { width: 960, height: 640, avif: "/media/tola-guest-word-960.avif", webp: "/media/tola-guest-word-960.webp" },
      { width: 1200, height: 800, avif: "/media/tola-guest-word-1200.avif", webp: "/media/tola-guest-word-1200.webp" },
      { width: 1440, height: 960, avif: "/media/tola-guest-word-1440.avif", webp: "/media/tola-guest-word-1440.webp" },
    ],
    category: "lanternHour",
    orientation: "landscape",
    fullBleedSafe: true,
  },
  {
    id: "tola-swimming",
    alt: "The pool at Mahua Tola.",
    width: 1163,
    height: 508,
    avif: "/media/tola-swimming-1163.avif",
    webp: "/media/tola-swimming-1163.webp",
    jpg: "/media/tola-swimming-1163.jpg",
    blur: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoYAAoAPu1mqk4ppaOiMAgBMB2JQBdmUABfZpmQwwxtCNgAAP7AQtWcdIdP8uNB0U7ZEQf9bxiv8KdyFB8/pbXMGWrjfLiZb7BnlHGydx7x36AA",
    sources: [
      { width: 400, height: 175, avif: "/media/tola-swimming-400.avif", webp: "/media/tola-swimming-400.webp" },
      { width: 640, height: 280, avif: "/media/tola-swimming-640.avif", webp: "/media/tola-swimming-640.webp" },
      { width: 768, height: 335, avif: "/media/tola-swimming-768.avif", webp: "/media/tola-swimming-768.webp" },
      { width: 960, height: 419, avif: "/media/tola-swimming-960.avif", webp: "/media/tola-swimming-960.webp" },
      { width: 1163, height: 508, avif: "/media/tola-swimming-1163.avif", webp: "/media/tola-swimming-1163.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: false,
  },
  {
    id: "vann-room-cottage-plain",
    alt: "A cottage at Mahua Vann — mud-plastered walls, a woven cane chair on the private sit-out, and the forest close through the glass doors.",
    width: 1440,
    height: 588,
    avif: "/media/vann-room-cottage-plain-1440.avif",
    webp: "/media/vann-room-cottage-plain-1440.webp",
    jpg: "/media/vann-room-cottage-plain-1440.jpg",
    blur: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQBACdASoYAAoAPu1iqk2ppaQiMAgBMB2JZACdMoC2AAZ6U77nQm40qQAAAP7AbQXFEgQBJ8l8fd0WhY5t5IgBC6EGrGcKnLzvitPyBk5gCEWt+X++NzBNJjkfHtulSjUJ6whmONfiFqaUAAA=",
    sources: [
      { width: 400, height: 163, avif: "/media/vann-room-cottage-plain-400.avif", webp: "/media/vann-room-cottage-plain-400.webp" },
      { width: 640, height: 261, avif: "/media/vann-room-cottage-plain-640.avif", webp: "/media/vann-room-cottage-plain-640.webp" },
      { width: 768, height: 314, avif: "/media/vann-room-cottage-plain-768.avif", webp: "/media/vann-room-cottage-plain-768.webp" },
      { width: 960, height: 392, avif: "/media/vann-room-cottage-plain-960.avif", webp: "/media/vann-room-cottage-plain-960.webp" },
      { width: 1200, height: 490, avif: "/media/vann-room-cottage-plain-1200.avif", webp: "/media/vann-room-cottage-plain-1200.webp" },
      { width: 1440, height: 588, avif: "/media/vann-room-cottage-plain-1440.avif", webp: "/media/vann-room-cottage-plain-1440.webp" },
    ],
    category: "lodgeLife",
    orientation: "landscape",
    fullBleedSafe: true,
  },
] as const;
