// GENERATED by scripts/build_welcome_logo.mjs — do not edit by hand.
//
// The client's stacked logo, split so the flower can turn and the wordmark
// cannot. Source is `Mahua-property-logos/Mahua-Resorts/Mahua-Resorts.png`; the
// encoded parts are `public/brand/welcome-{flower,wordmark}-*.webp`.
//
// **The fractions are the client's own layout**, measured off the artwork's ink
// rather than chosen, so re-laying the two parts out at these positions
// reproduces the original logo exactly. Redraw the logo, re-run the script, and
// everything below follows it.

export const WELCOME_LOGO = {
  /** The whole logo's intrinsic box, so nothing can disagree about its aspect. */
  width: 1361,
  height: 1299,
  /** Drawn widths of the whole logo, by breakpoint. The parts scale with it. */
  drawn: { phone: 190, wide: 280 },
  /** The part that turns. Position and size as fractions of the logo's box. */
  flower: { ...{"x":0.2116,"y":0,"w":0.5768,"h":0.6035}, widths: [162, 324, 486] as const },
  /** The part that must not. */
  wordmark: { ...{"x":0,"y":0.6844,"w":1,"h":0.3156}, widths: [280, 560, 840] as const },
} as const;
